### ISSUE TITLE
Hello? Is there docs about cloudcompare?

### ISSUE THREAD

**Issue by 459737087** [dwoiwode/pyCloudCompareCLI#6]
I don't know the interface about how to use the cloudcompare.

**Comment by dwoiwode** [comment]
Hi, there is a [wiki page](https://www.cloudcompare.org/doc/wiki/index.php?title=Command_line_mode) listing all the available commands. In this library you can chain them together with their original names and parameters as shown in the [example](https://github.com/dwoiwode/pyCloudCompareCLI/blob/master/examples/fileIO.py). 

What exactly do you want to know?

**Comment by 459737087** [comment]
Thank you, I want to test the distance between two points.
and I met a problem when I run cmd.execute()
[Errno 2] No such file or directory: '"/pyCloudCompareCLI/CloudCompare" -SILENT -O "/PointCloud.pcd" -C_EXPORT_FMT ASC -EXT xyz -SAVE_CLOUDS FILE "/newPointcloud.xyz"'

**Comment by dwoiwode** [comment]
It looks like your cloud compare executable does not exist. You are working on linux? To be honest I have no idea where the exectuable for cloudcompare is (see #4). 

Did you install cloud compare? The executable for running cloud compare in GUI should also work for the CLI.

If you can solve this issue I would be glad if you could provide a path to the default executable!

**Comment by dwoiwode** [comment]
Have you been able to solve your problem?

**Comment by 459737087** [comment]
Thank u , I have solved my problem.
