### ISSUE TITLE
Enum strings

### ISSUE THREAD

**Issue by alvaroalvarezih** [dwoiwode/pyCloudCompareCLI#8]
Based on class definition for several command options through pyCloudCompare.py, based on Enum definitions, for example: 

 class ROT(Enum):
    XYZ = "XYZ"
    X = "X"
    Y = "Y"
    Z = "Z"
    NONE = "NONE"

used for -ICP command, they should have an initial blank character to avoid errors on CloudCompare executions. This leads to definitions like;

class ROT(Enum):
    XYZ = " XYZ"
    X = " X"
    Y = " Y"
    Z = " Z"
    NONE = " NONE"
![1111](https://github.com/user-attachments/assets/f6f3ded7-02b0-4d3c-9d58-a46f3c420451)

**Comment by dwoiwode** [comment]
Thank you for finding this issue! I would rather fix this by fixing [this line](https://github.com/dwoiwode/pyCloudCompareCLI/blob/97e66db282052923b9a591055f65a80e15e5021f/pyCloudCompare/pyCloudCompare.py#L594) from `self.arguments.append("-ROT" + rot.value)` to `self.arguments += ["-ROT", rot.value]` as it is done with previous arguments. I will open a Merge request. It would be great if you could test whether this solution works :)

**Comment by alvaroalvarezih** [comment]
Perfect, this should work better!

**Comment by dwoiwode** [comment]
Should be fixed and published now as version 0.3.2. I hope it helps :)
